"""
Claude Says - A Tidbyt/Tronbyt app that displays a short creative
sentence generated by Claude.
"""

load("render.star", "render")
load("http.star", "http")
load("cache.star", "cache")
load("encoding/json.star", "json")
load("schema.star", "schema")

CLAUDE_API_URL = "https://api.anthropic.com/v1/messages"
CACHE_KEY = "claude_says_sentence"
CACHE_TTL = 900  # 15 minutes between new sentences

DEFAULT_PROMPT = "Write a single short witty sentence (under 60 characters) that would look fun on a tiny LED display. No quotes. Be creative, weird, poetic, or funny. Vary wildly each time."

def get_sentence(api_key):
    cached = cache.get(CACHE_KEY)
    if cached != None:
        return cached

    resp = http.post(
        CLAUDE_API_URL,
        headers = {
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        body = json.encode({
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 60,
            "messages": [
                {
                    "role": "user",
                    "content": DEFAULT_PROMPT,
                },
            ],
        }),
    )

    if resp.status_code != 200:
        return "Claude is napping..."

    data = resp.json()
    text = data["content"][0]["text"]

    # Trim to fit display reasonably
    if len(text) > 80:
        text = text[:77] + "..."

    cache.set(CACHE_KEY, text, ttl_seconds = CACHE_TTL)
    return text

def main(config):
    api_key = config.get("api_key", "")

    if api_key == "":
        sentence = "Set your Claude API key!"
    else:
        sentence = get_sentence(api_key)

    return render.Root(
        delay = 75,
        child = render.Box(
            padding = 1,
            child = render.Marquee(
                height = 30,
                scroll_direction = "vertical",
                child = render.Column(
                    cross_align = "center",
                    children = [
                        render.Text(
                            content = "Claude says:",
                            font = "tom-thumb",
                            color = "#d97706",
                        ),
                        render.Box(height = 2),
                        render.WrappedText(
                            content = sentence,
                            width = 62,
                            font = "tb-8",
                            color = "#c4b5fd",
                        ),
                    ],
                ),
            ),
        ),
    )

def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Text(
                id = "api_key",
                name = "Anthropic API Key",
                desc = "Your Anthropic API key for Claude",
                icon = "key",
            ),
        ],
    )
